-- data_monsters.lua
return {
  toSahurModels = {
    "Tri Tri Tri Tri Tri Tri Tri Tri Tri Tri Tri Tri Tri Tri Sarur",
    "Tri Tri Tri Tri Tri Tri Tri Tri Tri Tri Tri Tri Tri Sarur",
    "Tri Tri Tri Tri Tri Tri Tri Tri Tri Tri Tri Tri Sarur",
    "Tri Tri Tri Tri Tri Tri Tri Tri Tri Tri Tri Sarur",
    "Tri Tri Tri Tri Tri Tri Tri Tri Tri Tri Sarur",
    "Tri Tri Tri Tri Tri Tri Tri Tri Tri Sarur",
    "Tri Tri Tri Tri Tri Tri Tri Tri Sarur",
    "Tri Tri Tri Tri Tri Tri Tri Sarur",
    "Tri Tri Tri Tri Tri Tri Sarur",
    "Tri Tri Tri Tri Tri Sarur",
    "Tri Tri Tri Sarur",
  },

  weatherEventModels = {
    "Chicleteira",
    "YONII",
    "Coccodrillo Cheese",
    "Chachechchachachachi",
    "CanneIIoni Dragoni",
    "GALALTUS MEDUS",
    "Hipopotamino Supermakretino",
    "Market Crate",
    "BOSS",
    "MALAME AMARALE BOSS",
    "Malame Crate",
    "Las Vaquitas",
    "Trippi Troppi Troppa Trippa Boss",
    "Los Trippitroppito",
    "Trippi Troppi Troppa Trippa Boss2",
    "Blueberrinni Octossini Boss",
    "Blueberrinni Crate",
    "Los CrocodiIIitos",
    "Crocodillitos Crate",
    "Pipi Kiwi Boss",
    "Los OrcoIocos",
    "Pkin Kin Kin Kin Kin Kun",
    "Halloween2",
    "Drulimero Drulichina Boss",
  },

  forcedMonsters = {
    "Apple","Void Apple","Golden Apple","Golden Void Apple","Chick","Orange",
    "Bull","Brrr Brr Patapim","Acorn","Lirili LariIa","Trash Bag","Red Panda",
    "Tire","Rhino","Totem","Trippi Troppi Tropa Trippa","Box","Cacto Hipopootamo",
    "La Vaca Saturno Saturnita","Cactus","Boar","Urn","Chameleon","Treasure",
    "OrcaIero OrcaIa","Capuccino Assasino","Igloo","Tic Tac Tok Afammoc",
    "Pinkaroo","Frozen Fish","Blizzy","Marshmallow","Aurox","SaIamino Pinguino",
    "Toyboo","Spookit","Gear","Winding Key","Matteoo","Sea Urchin",
    "Gorillo WatermellondriIIo","Axolotus","Oyster","Rhino Rhino Toasterino",
    "Cog","Vault","Ecco CavaIIo Virtuoso","LeruIeruIeruIe","Helmet",
    "PeIicini Pananini","Pile of Gold","Cocossini Mamma","Pillar",
    "Espressona Signorra","Shimpanzini WatermeIonini Kingini","Ti Ti Ti Ti Sahur",
    "Car","Satellite Dish","Racotucotulu","Electricity Pole","Trenostruzzo Turbo 3K",
    "Nightmare Monster Sahur","Tombstone","TrikitrakateIas","Old Coffin",
    "Tang Tang Tang Tang Kelentang","Rune","AIessio","Ketupat Kepat Kupat Prekupat",
    "CentraIucci NucIearucci","Trash Pile","Radioactive Barrel","Big Pipe",
    "Dar Dir Durr Dorr TeIur Dadar","Tirilikalika TiriIikalako","BambercIat Crococlat",
    "TigrIIi Grapefrutunni","Brick","BuIbito Bandito Traktorito","Gangster Footeera",
    "Screw","BOSS","Tiny Stars","Tri Tri Tri Tri Sarur",
    -- Duplicates with weather list below are fine; farm.lua de-dupes:
    "Chicleteira","YONII","Coccodrillo Cheese","Chachechchachachachi",
    "CanneIIoni Dragoni","GALALTUS MEDUS","Hipopotamino Supermakretino",
    "Market Crate","BOSS","MALAME AMARALE BOSS","Malame Crate","Las Vaquitas",
    "Trippi Troppi Troppa Trippa Boss","Los Trippitroppito",
    "Trippi Troppi Troppa Trippa Boss2","Blueberrinni Octossini Boss",
    "Blueberrinni Crate","Los CrocodiIIitos","Crocodillitos Crate","Pipi Kiwi Boss",
  },
}
